### ISSUE TITLE
Send on closed channel in subscription

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#1333]
```
23:28:29.436  INFO keep-entry: [member:2] submitting relay entry [0x14ee9abbe50a50706e84b315095a74fcad4ac0bcb9e2f2226ec17b3e08d51afc135c61f0c22ed57361d7ca211e3fa27ac8660cd71449a2deaa565d40b228df06] on behalf of group [0x2f9c3228ffa406d8c625423592d8e79f616a89a34panic: send on closed channel

goroutine 86347 [running]:
github.com/keep-network/keep-core/pkg/beacon/relay/entry.(*relayEntrySubmitter).submitRelayEntry.func1(0xc0033011d8)
	/Users/piotr/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/entry/submission.go:42 +0x36
github.com/keep-network/keep-core/pkg/chain/ethereum.(*ethereumChain).OnRelayEntrySubmitted.func1(0x4f8)
	/Users/piotr/go/src/github.com/keep-network/keep-core/pkg/chain/ethereum/ethereum.go:255 +0x51
github.com/keep-network/keep-core/pkg/chain/gen/contract.(*KeepRandomBeaconOperator).subscribeRelayEntrySubmitted.func1(0xc000b300c0, 0xc0023532a8, 0xc000876b80, 0x4e25560, 0xc001e5ffc0, 0xc0026757a0)
	/Users/piotr/go/src/github.com/keep-network/keep-core/pkg/chain/gen/contract/KeepRandomBeaconOperator.go:2702 +0x133
created by github.com/keep-network/keep-core/pkg/chain/gen/contract.(*KeepRandomBeaconOperator).subscribeRelayEntrySubmitted
	/Users/piotr/go/src/github.com/keep-network/keep-core/pkg/chain/gen/contract/KeepRandomBeaconOperator.go:2692 +0x20b
```

**Comment by alphastorm** [comment]
Also related:
https://circleci.com/gh/keep-network/keep-core/53434 (from https://github.com/keep-network/keep-core/pull/1811)

**Comment by lionakhnazarov** [comment]
Closing as stale. Targets the legacy keep-core v1 (random beacon / KEEP staking) architecture, superseded by the Threshold v2 stack. Not actionable against current main.
