### ISSUE TITLE
beacon panic: close of closed channel

### ISSUE THREAD

**Issue by gregbostrom** [keep-network/keep-core#2052]
keepnetwork/keep-client:v1.3.0-rc.4

```
2020-09-15T01:52:28.992Z	DEBUG	keep-ethutil	packing parameters for method [relayEntry] with ABI [function relayEntry(bytes _groupSignature) returns()]: [[[24 185 223 129 138 59 78 0 133 201 192 182 195 6 131 29 74 163 249 19 147 19 99 100 66 25 131 23 123 111 49 30 1 232 18 78 112 67 85 205 247 238 7 161 152 56 225 2 190 173 14 35 68 162 200 32 250 143 159 221 124 224 210 136]]]
2020-09-15T01:52:28.992Z	DEBUG	keep-ethutil	resolving error for contract call [{From:[255 14 46 209 160 126 80 65 192 240 212 18 200 96 238 195 171 167 244 189] To:[200 51 122 148 165 13 22 25 21 19 222 244 209 230 26 104 134 191 65 15] Gas:0 GasPrice:<nil> Value:<nil> Data:[172 55 79 75 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 24 185 223 129 138 59 78 0 133 201 192 182 195 6 131 29 74 163 249 19 147 19 99 100 66 25 131 23 123 111 49 30 1 232 18 78 112 67 85 205 247 238 7 161 152 56 225 2 190 173 14 35 68 162 200 32 250 143 159 221 124 224 210 136]}]
2020-09-15T01:52:29.099Z	INFO	keep-relay	relay entry was submitted by the selected group on time at block [8687543]
panic: close of closed channel

goroutine 12138811 [running]:
github.com/keep-network/keep-core/pkg/chain/ethereum.(*ethereumChain).SubmitRelayEntry(0xc000168180, 0xc00f2657c0, 0x40, 0x40, 0xc004fabb08)
	/go/src/github.com/keep-network/keep-core/pkg/chain/ethereum/ethereum.go:203 +0x309
github.com/keep-network/keep-core/pkg/beacon/relay/entry.(*relayEntrySubmitter).submitRelayEntry(0xc00ed87860, 0xc00f2657c0, 0x40, 0x40, 0xc00f075f80, 0x80, 0x80, 0x848fb1, 0xc00f01e5a0, 0xc00f01e6c0, ...)
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/entry/submission.go:62 +0x628
github.com/keep-network/keep-core/pkg/beacon/relay/entry.SignAndSubmit(0x1470840, 0xc0000ce6c0, 0x1473700, 0xc0070c6360, 0x1485cc0, 0xc000168180, 0xc000511820, 0x40, 0xe0, 0x21, ...)
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/entry/entry.go:150 +0xbae
github.com/keep-network/keep-core/pkg/beacon/relay.(*Node).GenerateRelayEntry.func1(0xc008e18000, 0x1473700, 0xc0070c6360, 0x1485cc0, 0xc000168180, 0xc000511820, 0x40, 0xe0, 0x848fb1, 0xc001449150, ...)
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/relay.go:136 +0xd2
created by github.com/keep-network/keep-core/pkg/beacon/relay.(*Node).GenerateRelayEntry
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/relay.go:135 +0x328
```

And here is a bit bigger log snippet.
```
2020-09-15T01:52:23.428Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:23.428Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:23.428Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:23.428Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:23.429Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:23.430Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:23.508Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:23.508Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:25.250Z	DEBUG	addrutil	ResolveUnspecifiedAddresses:[/p2p-circuit /ip4/127.0.0.1/tcp/3919 /ip4/172.17.0.2/tcp/3919] [/ip4/172.17.0.2 /ip4/127.0.0.1] [/p2p-circuit /ip4/127.0.0.1/tcp/3919 /ip4/172.17.0.2/tcp/3919]
2020-09-15T01:52:25.250Z	DEBUG	keep-net-libp2p	replacing default announced addresses [[/ip4/127.0.0.1/tcp/3919 /ip4/172.17.0.2/tcp/3919 /ip4/107.152.47.162/tcp/3919]] with [[/ip4/107.152.47.162/tcp/3919]]
2020-09-15T01:52:28.572Z	INFO	keep-entry	[member:2] submitting relay entry [0x18b9df818a3b4e0085c9c0b6c306831d4aa3f91393136364421983177b6f311e01e8124e704355cdf7ee07a19838e102bead0e2344a2c820fa8f9fdd7ce0d288] on behalf of group [0x2941ac361bd822bab1796f04b16c339072f529c52101cc9a174e346dfd0252a51d737dd7f22ba24379237dc70f0c3d465653cf209c0f2e61781893d2c3be22ae2453cb89bd84a5b12bbac9cff5296a8a6692557cf594d52e1c04fd3c6cf998570a7e7990339fac095a1c66063d903a5475786ba26cbe8fdeb515c584d63f735f] at block [8687543]
2020-09-15T01:52:28.592Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.593Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.598Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.598Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.657Z	ERROR	keep-chain-ethereum	failed to estimate gas [gas required exceeds allowance (7999992) or always failing transaction]
2020-09-15T01:52:28.658Z	DEBUG	keep-contract-KeepRandomBeaconOperator	submitting transaction relayEntryparams: [24 185 223 129 138 59 78 0 133 201 192 182 195 6 131 29 74 163 249 19 147 19 99 100 66 25 131 23 123 111 49 30 1 232 18 78 112 67 85 205 247 238 7 161 152 56 225 2 190 173 14 35 68 162 200 32 250 143 159 221 124 224 210 136]
2020-09-15T01:52:28.686Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.686Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.726Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.726Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.748Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.748Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.761Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.761Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.762Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.763Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.811Z	DEBUG	keep-chain-ethereum	received gas price suggestion: [5000000000]
2020-09-15T01:52:28.956Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.956Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.957Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.957Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.965Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.965Z	WARN	keep-net-libp2p	message handler is too slow; dropping message
2020-09-15T01:52:28.992Z	DEBUG	keep-ethutil	packing parameters for method [relayEntry] with ABI [function relayEntry(bytes _groupSignature) returns()]: [[[24 185 223 129 138 59 78 0 133 201 192 182 195 6 131 29 74 163 249 19 147 19 99 100 66 25 131 23 123 111 49 30 1 232 18 78 112 67 85 205 247 238 7 161 152 56 225 2 190 173 14 35 68 162 200 32 250 143 159 221 124 224 210 136]]]
2020-09-15T01:52:28.992Z	DEBUG	keep-ethutil	resolving error for contract call [{From:[255 14 46 209 160 126 80 65 192 240 212 18 200 96 238 195 171 167 244 189] To:[200 51 122 148 165 13 22 25 21 19 222 244 209 230 26 104 134 191 65 15] Gas:0 GasPrice:<nil> Value:<nil> Data:[172 55 79 75 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 24 185 223 129 138 59 78 0 133 201 192 182 195 6 131 29 74 163 249 19 147 19 99 100 66 25 131 23 123 111 49 30 1 232 18 78 112 67 85 205 247 238 7 161 152 56 225 2 190 173 14 35 68 162 200 32 250 143 159 221 124 224 210 136]}]
2020-09-15T01:52:29.099Z	INFO	keep-relay	relay entry was submitted by the selected group on time at block [8687543]
panic: close of closed channel

goroutine 12138811 [running]:
github.com/keep-network/keep-core/pkg/chain/ethereum.(*ethereumChain).SubmitRelayEntry(0xc000168180, 0xc00f2657c0, 0x40, 0x40, 0xc004fabb08)
	/go/src/github.com/keep-network/keep-core/pkg/chain/ethereum/ethereum.go:203 +0x309
github.com/keep-network/keep-core/pkg/beacon/relay/entry.(*relayEntrySubmitter).submitRelayEntry(0xc00ed87860, 0xc00f2657c0, 0x40, 0x40, 0xc00f075f80, 0x80, 0x80, 0x848fb1, 0xc00f01e5a0, 0xc00f01e6c0, ...)
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/entry/submission.go:62 +0x628
github.com/keep-network/keep-core/pkg/beacon/relay/entry.SignAndSubmit(0x1470840, 0xc0000ce6c0, 0x1473700, 0xc0070c6360, 0x1485cc0, 0xc000168180, 0xc000511820, 0x40, 0xe0, 0x21, ...)
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/entry/entry.go:150 +0xbae
github.com/keep-network/keep-core/pkg/beacon/relay.(*Node).GenerateRelayEntry.func1(0xc008e18000, 0x1473700, 0xc0070c6360, 0x1485cc0, 0xc000168180, 0xc000511820, 0x40, 0xe0, 0x848fb1, 0xc001449150, ...)
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/relay.go:136 +0xd2
created by github.com/keep-network/keep-core/pkg/beacon/relay.(*Node).GenerateRelayEntry
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/relay.go:135 +0x328
2020-09-15T01:52:31.658Z	DEBUG	keep-block-counter	subscribing to new blocks
2020-09-15T01:52:32.465Z	INFO	keep-chain-ethereum	using [1m0s] mining check interval
2020-09-15T01:52:32.466Z	INFO	keep-chain-ethereum	using [500000000000] wei max gas price
2020-09-15T01:52:32.470Z	INFO	keep-chain-ethereum	fetching relay chain config
```

**Comment by gregbostrom** [comment]
[2minlog.txt](https://github.com/keep-network/keep-core/files/5228049/2minlog.txt)

**Comment by pdyraga** [comment]
Thank you for submitting the issue @gregbostrom 🙌 This is indeed a problem, same as https://github.com/keep-network/keep-core/issues/1333, that should be solved during the work on https://github.com/keep-network/keep-core/issues/491.

**Comment by lionakhnazarov** [comment]
Closing as stale. Targets the legacy keep-core v1 (random beacon / KEEP staking) architecture, superseded by the Threshold v2 stack. Not actionable against current main.
