### ISSUE TITLE
Panic during ticket submission

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/keep-core#2072]
One of the `keep-core` clients exited due to a panic error while taking part in the ticket submission process:

```
panic: runtime error: slice bounds out of range [:20] with capacity 19 goroutine 2372 [running]: github.com/keep-network/keep-core/pkg/chain/ethereum.(*ethereumChain).packTicket(0xc00015c0c0, 0xc000448920, 0x0, 0x0, 0x0, 0x0) /go/src/github.com/keep-network/keep-core/pkg/chain/ethereum/ethereum.go:81 +0x42b github.com/keep-network/keep-core/pkg/chain/ethereum.(*ethereumChain).SubmitTicket(0xc00015c0c0, 0xc000448920, 0x0) /go/src/github.com/keep-network/keep-core/pkg/chain/ethereum/ethereum.go:61 +0x89 github.com/keep-network/keep-core/pkg/beacon/relay/groupselection.submitTicketsOnChain(0xc0001a6f40, 0x3, 0x4, 0x7f0cc94e2bd0, 0xc00015c0c0) /go/src/github.com/keep-network/keep-core/pkg/beacon/relay/groupselection/ticket_submission.go:24 +0xf5 github.com/keep-network/keep-core/pkg/beacon/relay/groupselection.submitTickets(0xc000531200, 0x32, 0x40, 0x7f0cc94e2bd0, 0xc00015c0c0, 0x1470840, 0xc0003e8900, 0xc00003c8d0, 0x152, 0x0, ...) /go/src/github.com/keep-network/keep-core/pkg/beacon/relay/groupselection/groupselection.go:185 +0x1b9 github.com/keep-network/keep-core/pkg/beacon/relay/groupselection.CandidateToNewGroup(0x1485cc0, 0xc00015c0c0, 0x1470840, 0xc0003e8900, 0xc00003c8d0, 0x145fb00, 0xc0001a6ea0, 0xc0005f31a0, 0x152, 0xc0007e9e00, ...) /go/src/github.com/keep-network/keep-core/pkg/beacon/relay/groupselection/groupselection.go:93 +0x31d github.com/keep-network/keep-core/pkg/beacon.Initialize.func2.2(0xc00025a5f0, 0xc00020b280, 0x40, 0xc0005fa800, 0x1485cc0, 0xc00015c0c0, 0x1470840, 0xc0003e8900, 0xc00003c8d0, 0x145fb00, ...) /go/src/github.com/keep-network/keep-core/pkg/beacon/beacon.go:168 +0x21b created by github.com/keep-network/keep-core/pkg/beacon.Initialize.func2 /go/src/github.com/keep-network/keep-core/pkg/beacon/beacon.go:151 +0x1d1
```

**Comment by kferretcrypto** [comment]
I had a similar panic. Is this a known issue or something to worry about?

```
panic: runtime error: slice bounds out of range [:20] with capacity 15
goroutine 215728 [running]:
github.com/keep-network/keep-core/pkg/chain/ethereum.(*ethereumChain).packTicket(0xc0001b0180, 0xc000fea120, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/keep-network/keep-core/pkg/chain/ethereum/ethereum.go:81 +0x42b
github.com/keep-network/keep-core/pkg/chain/ethereum.(*ethereumChain).SubmitTicket(0xc0001b0180, 0xc000fea120, 0x0)
/go/src/github.com/keep-network/keep-core/pkg/chain/ethereum/ethereum.go:61 +0x89
github.com/keep-network/keep-core/pkg/beacon/relay/groupselection.submitTicketsOnChain(0xc0000102e0, 0x1, 0x1, 0x7ff06f59e998, 0xc0001b0180)
/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/groupselection/ticket_submission.go:24 +0xf5
github.com/keep-network/keep-core/pkg/beacon/relay/groupselection.submitTickets(0xc00011a518, 0x1, 0x1, 0x7ff06f59e998, 0xc0001b0180, 0x1470880, 0xc0001fc080, 0xc00010d110, 0xa6bfd8, 0x0, ...)
/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/groupselection/groupselection.go:185 +0x1b9
github.com/keep-network/keep-core/pkg/beacon/relay/groupselection.CandidateToNewGroup(0x1485d00, 0xc0001b0180, 0x1470880, 0xc0001fc080, 0xc00010d110, 0x145fb00, 0xc0000bc8c0, 0xc000433ea0, 0xa6bfd8, 0xc000a01380, ...)
/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/groupselection/groupselection.go:93 +0x31d
github.com/keep-network/keep-core/pkg/beacon.Initialize.func2.2(0xc0001c0d40, 0xc000b7a840, 0x40, 0xc001176690, 0x1485d00, 0xc0001b0180, 0x1470880, 0xc0001fc080, 0xc00010d110, 0x145fb00, ...)
/go/src/github.com/keep-network/keep-core/pkg/beacon/beacon.go:168 +0x21b
created by github.com/keep-network/keep-core/pkg/beacon.Initialize.func2
/go/src/github.com/keep-network/keep-core/pkg/beacon/beacon.go:151 +0x1d1
```

@lukasz-zimnoch Has this issue been recurring for you, or was it a one-time issue?

**Comment by kferretcrypto** [comment]
I noticed that this looks like an issue with stakerValue, which I believe is the operator address. My operator address has a lot of 0's in the front. Does yours also? @lukasz-zimnoch

**Comment by kferretcrypto** [comment]
I have a hypothesis on what is happening. The StakerValue is the operator address. It is expected to be 20 bytes and it is not padded if it is less than that. My address starts with many 0's (0x0000...), so therefore it is less than 20 bytes. The code for packTicket (https://github.com/keep-network/keep-core/blob/b345efd7bdd6c9521bcc04011a934f17e851df56/pkg/chain/ethereum/ethereum.go#L81) tries to slice [0:20]. Therefore it fails on addresses less than 20 bytes. If this is the case, the client will not be able to submit tickets for anyone with an address that has fewer than 20 bytes (that starts with a pair of 0's or more).

@pdyraga @Shadowfiend

**Comment by knarz** [comment]
A quick investigation seems to show that in `ticket.go` the `StakerValue` is actually padded

https://github.com/keep-network/keep-core/blob/b345efd7bdd6c9521bcc04011a934f17e851df56/pkg/beacon/relay/groupselection/ticket.go#L66

but above that it is passed into the struct without padding

https://github.com/keep-network/keep-core/blob/b345efd7bdd6c9521bcc04011a934f17e851df56/pkg/beacon/relay/groupselection/ticket.go#L36-L48

**Comment by kferretcrypto** [comment]
Just for anyone who might be following this issue, @Shadowfiend, @knarz, and I discussed this on Discord. The issue only prevents those with addresses beginning with 0x00 from participating in random beacon. Based on the issue we identified, there is no risk of losing stake or any other funds, so it is not an emergency and the team will take a closer look tomorrow.

**Comment by mhluongo** [comment]
Appreciate the follow-through and reproduction guys

**Comment by pdyraga** [comment]
Thanks for the analysis guys, we'll work on it as soon as possible.

**Comment by lukasz-zimnoch** [comment]
Thanks for the investigation @kferretcrypto, @knarz! #2094 should fix the problem.
