### ISSUE TITLE
Ocasionally failing TokenStakingEscrow test

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#2167]
The following test is failing occasionally on some timing issue:
```
   1) TokenStakingEscrow
       withdrawRevoked
         withdraws part of deposited amount if something has been withdrawn before:
     AssertionError: expected 149999884259259259259260 to equal 150000000000000000000000
      at Context.<anonymous> (test/token_stake/TestTokenStakingEscrow.js:531:26)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by lionakhnazarov** [comment]
Closing as stale. Targets the legacy keep-core v1 (random beacon / KEEP staking) architecture, superseded by the Threshold v2 stack. Not actionable against current main.
