### ISSUE TITLE
Ocasionally failing GJKR integration tests

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#2168]
GJKR integration tests are occasionally failing with `panic: send on closed channel`. We do have the refactoring of subscriptions planned in https://github.com/keep-network/keep-core/issues/491 but maybe there is something else we can do short-term to improve the situation.
 
```
=== Failed
=== FAIL: pkg/beacon/relay/gjkr TestExecute_IA_member1_phase8 (429.30s)
failed with: [[member:3] could not stay in the group because member is considered as misbehaving]
failed with: [[member:5] could not stay in the group because member is considered as misbehaving]
panic: send on closed channel

goroutine 60952 [running]:
github.com/keep-network/keep-core/pkg/beacon/relay/dkg/result.(*SubmittingMember).SubmitDKGResult.func1(0xc000585380)
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/dkg/result/submission.go:74 +0x3a
github.com/keep-network/keep-core/pkg/chain/local.(*localChain).SubmitDKGResult.func1(0xc000585380, 0xc000796ee0, 0xc000585380)
	/go/src/github.com/keep-network/keep-core/pkg/chain/local/local.go:445 +0x30
created by github.com/keep-network/keep-core/pkg/chain/local.(*localChain).SubmitDKGResult
	/go/src/github.com/keep-network/keep-core/pkg/chain/local/local.go:444 +0x475
FAIL	github.com/keep-network/keep-core/pkg/beacon/relay/gjkr	429.299s
```

**Comment by lionakhnazarov** [comment]
Closing as stale. Targets the legacy keep-core v1 (random beacon / KEEP staking) architecture, superseded by the Threshold v2 stack. Not actionable against current main.
