### ISSUE TITLE
Fix v1 Go tests sometimes failing with `could not stay in the group because member is considered as misbehaving`

### ISSUE THREAD

**Issue by michalinacienciala** [keep-network/keep-core#3022]
The `keep-core` `Go` workflow has failed with following errors:
```
=== Failed
=== FAIL: pkg/beacon/relay/gjkr TestExecute_DQ_member2_invalidMessage_phase8 (unknown)
=== FAIL: pkg/beacon/relay/gjkr TestExecute_DQ_member2_accusesInactiveMember_phase9 (unknown)
=== FAIL: pkg/beacon/relay/gjkr TestExecute_DQ_member2_revealedKeyOfOperatingMember_phase11 (unknown)
failed with: [[member:4] could not stay in the group because member is considered as misbehaving]
failed with: [[member:5] could not stay in the group because member is considered as misbehaving]
panic: send on closed channel
goroutine 52883 [running]:
github.com/keep-network/keep-core/pkg/beacon/relay/dkg/result.(*SubmittingMember).SubmitDKGResult.func1(0xc000504940)
	/go/src/github.com/keep-network/keep-core/pkg/beacon/relay/dkg/result/submission.go:[74](https://github.com/keep-network/keep-core/runs/6839544867?check_suite_focus=true#step:7:75) +0x3a
github.com/keep-network/keep-core/pkg/chain/local.(*localChain).SubmitDKGResult.func1(0xc000504940, 0xc0008[76](https://github.com/keep-network/keep-core/runs/6839544867?check_suite_focus=true#step:7:77)2e0, 0xc000504940)
	/go/src/github.com/keep-network/keep-core/pkg/chain/local/local.go:446 +0x30
created by github.com/keep-network/keep-core/pkg/chain/local.(*localChain).SubmitDKGResult
	/go/src/github.com/keep-network/keep-core/pkg/chain/local/local.go:445 +0x4[79](https://github.com/keep-network/keep-core/runs/6839544867?check_suite_focus=true#step:7:80)
=== FAIL: pkg/beacon/relay/gjkr TestExecute_DQ_members25_revealWrongPrivateKey_phase9 (unknown)
=== FAIL: pkg/beacon/relay/gjkr TestExecute_DQ_members14_invalidPublicKeyShare_phase9 (unknown)
=== FAIL: pkg/beacon/relay/gjkr TestExecute_DQ_member5_revealsWrongPrivateKey_phase11 (unknown)
failed with: [[member:2] could not stay in the group because member do not support the same group public key]
failed with: [[member:1] could not stay in the group because member do not support the same group public key]
=== FAIL: pkg/beacon/relay/gjkr TestExecute_DQ_member4_falseAccusation_phase9 (unknown)
=== FAIL: pkg/beacon/relay/gjkr TestExecute_DQ_members12_cannotDecryptTheirShares_phase9 (unknown)
```

Workflow: https://github.com/keep-network/keep-core/runs/6839544867?check_suite_focus=true.

This isn't the first time we see similar errors (although they don't occur often). Last time we discussed this it was concluded that:

"We need to solve the first one but we don't have any spare cycles at the moment 😦 it's something about libp2p upgrade [...] It could be something about the unit test or something about the channel implementation."

**Comment by michalinacienciala** [comment]
Another execution with similar failure (no `could not stay in the group because member is considered as misbehaving`, but there was the `could not stay in the group because member do not support the same group public key` error in there): https://github.com/keep-network/keep-core/runs/7103196422?check_suite_focus=true.

**Comment by lionakhnazarov** [comment]
Closing as stale. Targets the legacy keep-core v1 (random beacon / KEEP staking) architecture, superseded by the Threshold v2 stack. Not actionable against current main.
