### ISSUE TITLE
Linking projects with yarn

### ISSUE THREAD

**Issue by dimpar** [keep-network/keep-core#3312]
It happens occasionally, that after calling `install.sh` yarn linking won't work correctly which will result in the following error:
```
tslabon@MacBook-Pro-Tomasz ~/projekt/keep-core $% ./scripts/initialize.sh --stake-owner  0x037d7fbca1ca96e6d628c2b8fd910c59a8aa213c

Initializing beacon...
An unexpected error occurred:

Error: No deployment found for: TokenStaking
    at Object.get (/Users/tslabon/projekt/keep-core/solidity/random-beacon/node_modules/hardhat-deploy/src/DeploymentsManager.ts:162:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

The quick workaround it so to navigate manually to `/solidity/random-beacon` and executing `yarn link @threshold-network/solidity-contracts`, but this should all happen in `install.sh` automatically.

**Comment by lionakhnazarov** [comment]
Closing as stale. Legacy infra/CI/local-dev task that no longer matches current tooling (Yarn 4, updated workflows, v2 stack) on main.
