### ISSUE TITLE
Pad R/S signature bytes hex when printing heartbeat

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3489]
I think the client does not pad S signature correctly when logging heartbeat message.

Compare please:
```
2023-01-30T19:06:21.398Z    INFO    keep-tbtc    tbtc/signing.go:153    generated signature [R: 0xd244b4b44e4160c2aac0b65d27c988f31e72906f7ae8d9f087be882278b05339, S: 0x70ee7d033fcda16f05bcc54f20f5a3cc4683aa454adab9fde5ab08447bf81c07, RecoveryID: 1] for message at block [16521620]    {"wallet": "0x04b0a483e97dfbb15e88ecbc2ef8f7e37776dd713eed54089f87704a4fbae0442aa3ff5a0ec7f4d52bf4680b5b9b70be9accb64970df11b96abb61d48be7d8db8b", "messages": "0xbe6c...b41e, 0xdfdb...61ca, 0x5e99...a818, 0xdaa6...88e7, 0x80c4...ec27", "message": "0xbe6ce81da6f4ca05ca2858a17c051417bd9abef5eec21a41676e2a0f6c84b41e", "index": "1/5"}
2023-01-30T19:10:21.529Z    INFO    keep-tbtc    tbtc/signing.go:153    generated signature [R: 0x2efe1aa7a56fc80d7f0354846257e37995a37da44721887ad51599fd9fdbee11, S: 0x27e767ca6b7a0f075a8039de7836f373b120122a742a78bb14832fb4476179d, RecoveryID: 1] for message at block [16521640]    {"wallet": "0x04b0a483e97dfbb15e88ecbc2ef8f7e37776dd713eed54089f87704a4fbae0442aa3ff5a0ec7f4d52bf4680b5b9b70be9accb64970df11b96abb61d48be7d8db8b", "messages": "0xbe6c...b41e, 0xdfdb...61ca, 0x5e99...a818, 0xdaa6...88e7, 0x80c4...ec27", "message": "0xdfdbeb3dce0eebfef8ebf927a38da77adfd59c0e037baf132170182aaa2461ca", "index": "2/5"}
```
```
0x70ee7d033fcda16f05bcc54f20f5a3cc4683aa454adab9fde5ab08447bf81c07
0x27e767ca6b7a0f075a8039de7836f373b120122a742a78bb14832fb4476179d
```

And then: 
```
❯ ./ecdsa.ts verify 0x04b0a483e97dfbb15e88ecbc2ef8f7e37776dd713eed54089f87704a4fbae0442aa3ff5a0ec7f4d52bf4680b5b9b70be9accb64970df11b96abb61d48be7d8db8b 0xdfdbeb3dce0eebfef8ebf927a38da77adfd59c0e037baf132170182aaa2461ca 0x2efe1aa7a56fc80d7f0354846257e37995a37da44721887ad51599fd9fdbee11 0x0027e767ca6b7a0f075a8039de7836f373b120122a742a78bb14832fb4476179d 1
/Users/piotr/git/nkuba/ecdsa-ts/ecdsa.ts:77
    throw new Error(`hex value length is not even: ${value}`)
Error: hex value length is not even: 0x0027e767ca6b7a0f075a8039de7836f373b120122a742a78bb14832fb4476179d
    at decodeHex (/Users/piotr/git/nkuba/ecdsa-ts/ecdsa.ts:77:11)
    at Command.<anonymous> (/Users/piotr/git/nkuba/ecdsa-ts/ecdsa.ts:23:32)
(...)
```

But when I left-pad with one 0:
```
❯ ./ecdsa.ts verify 0x04b0a483e97dfbb15e88ecbc2ef8f7e37776dd713eed54089f87704a4fbae0442aa3ff5a0ec7f4d52bf4680b5b9b70be9accb64970df11b96abb61d48be7d8db8b 0xdfdbeb3dce0eebfef8ebf927a38da77adfd59c0e037baf132170182aaa2461ca 0x2efe1aa7a56fc80d7f0354846257e37995a37da44721887ad51599fd9fdbee11 0x027e767ca6b7a0f075a8039de7836f373b120122a742a78bb14832fb4476179d 1
verifying ECDSA signature on secp256k1 curve
uncompressed public key: 04b0a483e97dfbb15e88ecbc2ef8f7e37776dd713eed54089f87704a4fbae0442aa3ff5a0ec7f4d52bf4680b5b9b70be9accb64970df11b96abb61d48be7d8db8b
message: dfdbeb3dce0eebfef8ebf927a38da77adfd59c0e037baf132170182aaa2461ca
signature:
r          : 2efe1aa7a56fc80d7f0354846257e37995a37da44721887ad51599fd9fdbee11
s          : 027e767ca6b7a0f075a8039de7836f373b120122a742a78bb14832fb4476179d
recovery ID: 1

SIGNATURE IS VALID!
```

**Comment by nkuba** [comment]
True, the fix has been already waiting in the queue: https://github.com/keep-network/keep-core/pull/3477
